SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE `pc-event`.`events` ADD COLUMN `pic_small` VARCHAR(200) NULL DEFAULT '' COMMENT '小照片\n36*36'  AFTER `gmt_modified` , ADD COLUMN `pic_normal` VARCHAR(200) NULL DEFAULT '' COMMENT '普通大小\n96*96'  AFTER `pic_small` , ADD COLUMN `pic_larger` VARCHAR(200) NULL DEFAULT '' COMMENT '较大\n128*128'  AFTER `pic_normal` , ADD COLUMN `pic_banner` VARCHAR(200) NULL DEFAULT '' COMMENT 'Banner'  AFTER `pic_larger` ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
