-- MySQL Workbench Synchronization
-- Generated: 2016-01-14 11:47
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: mays

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `pc-erp`.`everyday` 
CHANGE COLUMN `wx_openid` `wx_openid` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '关注者的微信号' ,
CHANGE COLUMN `url` `url` VARCHAR(2000) NULL DEFAULT '' COMMENT '相关 URL' ,
CHANGE COLUMN `content` `content` LONGTEXT NULL DEFAULT NULL COMMENT '记录的内容' ,
CHANGE COLUMN `tags` `tags` VARCHAR(250) NULL DEFAULT NULL COMMENT '标签' ,
ADD COLUMN `wx_msgid` VARCHAR(45) NULL DEFAULT NULL AFTER `wx_openid`,
ADD COLUMN `day_index` INT(11) NULL DEFAULT 0 COMMENT '连续天数索引' AFTER `tags`,
ADD COLUMN `day_item_index` INT(11) NULL DEFAULT 0 COMMENT '每天信息索引' AFTER `day_index`,
ADD COLUMN `wx_msgtype` VARCHAR(45) NULL DEFAULT NULL AFTER `day_item_index`,
ADD COLUMN `wx_picurl` VARCHAR(2000) NULL DEFAULT NULL AFTER `wx_msgtype`,
ADD COLUMN `wx_mediaid` VARCHAR(45) NULL DEFAULT NULL AFTER `wx_picurl`,
ADD COLUMN `wx_thumb_media_id` VARCHAR(45) NULL DEFAULT NULL AFTER `wx_mediaid`,
ADD COLUMN `wx_lx` DECIMAL(10,6) NULL DEFAULT NULL AFTER `wx_thumb_media_id`,
ADD COLUMN `wx_ly` DECIMAL(10,6) NULL DEFAULT NULL AFTER `wx_lx`,
ADD COLUMN `wx_scale` VARCHAR(200) NULL DEFAULT NULL AFTER `wx_ly`,
ADD COLUMN `wx_label` VARCHAR(200) NULL DEFAULT NULL AFTER `wx_scale`,
ADD COLUMN `wx_title` VARCHAR(200) NULL DEFAULT NULL AFTER `wx_label`,
ADD COLUMN `wx_description` VARCHAR(250) NULL DEFAULT NULL AFTER `wx_title`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
